r"""Which numbers a rewritten bullet is allowed to contain. Spec 5, `verify_grounding`.

    nums_generated = set(re.findall(r'\d+(?:\.\d+)?%?', tailored.text))
    nums_allowed   = allowed_number_forms(source.metrics)   # 820 -> {"820", "820ms", "0.82s"}
    assert nums_generated <= nums_allowed

CLAUDE.md rule 1: "Every number must trace to a key in that bullet's `metrics`
dict." Spec 3.1 calls this constraint the thing that "kills 90% of resume
hallucination, and it's checkable with a regex, not a judge."

Two design points do the real work here.

**Numbers already in the canonical text are allowed.** Without this the check is
unusable: `"eliminating N+1 queries across 12 endpoints"` contains a literal 1
that belongs to no metric, and every truthful rephrasing would be rejected. The
rule being enforced is *new numbers must trace to metrics* -- not that every
digit on the page must.

**Re-expression is allowed; arithmetic is not.** A rewrite may say 0.82s where
the source says 820ms, or 1.2M where the source says 1200000 -- same quantity,
different surface form. It may **not** say "a 94% reduction" derived from a
before and an after, because that is a new fact the source never asserted. So
this module generates unit conversions and magnitude scalings, and deliberately
never generates differences, ratios or percentage changes between metrics.
"""

from __future__ import annotations

import re

from resume_agent.models.profile import MetricValue

# A numeric quantity: optional currency, digits with optional thousands
# separators and decimals, an optional magnitude suffix, an optional percent.
#
# The lookbehind excludes digits glued to a preceding word character, so "p95"
# and "N1" are read as names rather than as quantities. The magnitude suffix is
# uppercase-only and must not be followed by a lowercase letter, so "2M" is a
# magnitude but the "m" in "820ms" is a unit and stays out of the number.
_NUMBER_RE = re.compile(
    r"(?<![\w.])"
    r"\$?"
    r"(\d[\d,]*(?:\.\d+)?)"
    r"([KMB](?![a-z]))?"
    r"%?"
)

_MAGNITUDES = {"K": 1_000, "M": 1_000_000, "B": 1_000_000_000}

# Unit hints read off the end of a metric key. `latency_before_ms` is 820
# milliseconds, so 0.82 seconds is the same fact said differently.
_UNIT_CONVERSIONS: dict[str, list[float]] = {
    "_ms": [1 / 1000],  # -> seconds
    "_s": [1000],  # -> milliseconds
    "_sec": [1000],
    "_min": [60, 1 / 60],  # -> seconds, hours
    "_hours": [60],  # -> minutes
    "_days": [24],  # -> hours
}


def _canonical_number(value: float) -> str:
    """One normalised string per numeric value, so 1,200,000 and 1.2M compare equal."""
    if value == int(value):
        return str(int(value))
    # Trim float noise from the scaling arithmetic without losing real precision.
    return f"{value:.6f}".rstrip("0").rstrip(".")


def extract_numbers(text: str) -> set[str]:
    """Every numeric quantity in `text`, normalised."""
    found: set[str] = set()
    for digits, magnitude in _NUMBER_RE.findall(text):
        value = float(digits.replace(",", ""))
        if magnitude:
            value *= _MAGNITUDES[magnitude]
        found.add(_canonical_number(value))
    return found


def _scaled_forms(value: float, key: str) -> set[str]:
    """Every legitimate way of writing one metric value."""
    forms = {_canonical_number(value)}

    lowered = key.lower()
    for suffix, factors in _UNIT_CONVERSIONS.items():
        if lowered.endswith(suffix):
            for factor in factors:
                forms.add(_canonical_number(value * factor))

    # A percentage may be written either as 94 or as 0.94, in both directions.
    if lowered.endswith(("_pct", "_percent", "_rate")):
        forms.add(_canonical_number(value / 100))
    if 0 < abs(value) < 1:
        forms.add(_canonical_number(value * 100))

    # Magnitudes: 2000000 may be written 2M, 4100000 as 4.1M. Generated by
    # scaling *down*, then re-normalised -- so the allowed set contains the
    # expanded value either way and "2M" in a rewrite normalises to match.
    for factor in _MAGNITUDES.values():
        if abs(value) >= factor:
            scaled = value / factor
            forms.add(_canonical_number(round(scaled, 1)))
            forms.add(_canonical_number(round(scaled)))

    return forms


def allowed_number_forms(metrics: dict[str, MetricValue], canonical: str = "") -> set[str]:
    """Every number a rewrite of this bullet may legitimately contain.

    The union of:
      * numbers already present in the source sentence, and
      * every re-expression of each value in the `metrics` dict.
    """
    allowed = extract_numbers(canonical)

    for key, raw in metrics.items():
        if isinstance(raw, bool):
            continue  # bools are not quantities
        if isinstance(raw, int | float):
            allowed |= _scaled_forms(float(raw), key)
        else:
            # A string metric like "99.95%" or "3 regions": take the numbers out
            # of it and treat each as a value in its own right.
            for number in extract_numbers(str(raw)):
                allowed |= _scaled_forms(float(number), key)

    return allowed


def unsupported_numbers(
    text: str, metrics: dict[str, MetricValue], canonical: str = ""
) -> set[str]:
    """Numbers in `text` that trace to neither the metrics nor the source sentence.

    A non-empty result is a fabrication: the rewrite asserts a quantity that the
    knowledge base does not contain.
    """
    return extract_numbers(text) - allowed_number_forms(metrics, canonical)
